
a = input("Digite algo: ")
print('O tipo primitivo desse valor é: ', type(a))
print('Só tem espaços? ', a.isspace())
print('É um numero inteiro? ', a.isnumeric())
print('É alfabético? ', a.isalpha())
print('É alfanumérico? ', a.isalnum())
print('Está em Maiúscula? ', a.isupper())
print('Está em Minúscula? ', a.islower())
print('Está capitalizada? ', a.istitle())